### ISSUE TITLE
Deployment on Azure using Docker

### ISSUE THREAD

**Issue by Pugsrgreat** [NebulaServices/Nebula#101]
I am extremely impressed with the performance and the UI on this site, but deployment is very complicated. I have tried a few different methods, including all of the template links, I also tried to deploy the code to an azure app service (web app). Which I was unsuccessful at doing, so I would like to ask if there are steps to building the docker container for use with azure, because those tend to work better.

**Comment by GreenyDEV** [comment]
To be completely honest, our support regarding the templates are pretty limited. If you have SSH access to the VPS, I would definitely recommend following the documentation we provide on deployment, specifically the [Advanced deployment guide.](https://docs.nebulaproxy.io/services/nebulaweb/deployment.html#advanced-deployment
)
You can also check [The Canary Repository](https://git.nebulaproxy.dev/NebulaServices/nebula-canary) for upcoming features before they are pushed here. 

Supporting multiple platforms is difficult, and as we refactor our codebase we hope to continue to improve the ease of use.
We also allow open contribution with Pull Requests.

**Comment by Pugsrgreat** [comment]
I will try that and find a way to make a deployment template for you Sent from my iPhoneOn Apr 27, 2023, at 11:20 AM, Green! ***@***.***> wrote:﻿
To be completely honest, our support regarding the templates are pretty limited. If you have SSH access to the VPS, I would definitely recommend following the documentation we provide on deployment, specifically the Advanced deployment guide.
You can also check The Canary Repository for upcoming features before they are pushed here.
Supporting multiple platforms is difficult, and as we refactor our codebase we hope to continue to improve the ease of use.
We also allow open contribution with Pull Requests.

**Comment by GreenyDEV** [comment]
🙏
