### ISSUE TITLE
Issue with Deployment to Render

### ISSUE THREAD

**Issue by D3RPYC4T-dev** [NebulaServices/Nebula#102]
Since yesterday the Render deployment I had been using stopped working and I still don't entirely know why, but every time I try to open a site through it it gives me the error "SyntaxError: Unexpected token 'd', "dial tcp 1"... is not valid JSON" and then doesn't load the site. It was working fine the day before but only gives me this error now. My original guess was that it had something to do with the older cloned version of the Nebula repo I had been using before there was a render.yaml file set up in the official Nebula repo, though everytime I try to deploy from this Nebula repo render won't ler me deploy and says "an error has occurred (invalid repository)".
Note: I also opened a ticket in the Nebula Services discord mentioning the same issue

**Comment by GreenyDEV** [comment]
Moving to discord ticket, https://discord.gg/unblocker
