### ISSUE TITLE
Ultraviolet error

### ISSUE THREAD

**Issue by valiantuser** [NebulaServices/Nebula#106]
I deployed Nebula through Railway and It was successful. When I try to use Ultraviolet on Nebula, It gives me an error.

"SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON"

Note, that I used the "Deploy to Railway" button when deploying Nebula.

![Screenshot 2023-05-01 6 41 35 PM](https://user-images.githubusercontent.com/101596581/235544005-7b0959d9-8ca8-44f7-84d5-53922a0cc9be.png)

**Comment by 830008** [comment]
Did you create a ticket?

**Comment by valiantuser** [comment]
> Did you create a ticket?

No, I will make one right now.
