### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by zek-c** [NebulaServices/Nebula#107]
"SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON"

**Comment by GreenyDEV** [comment]
Not a valid issue

**Comment by EnforcedPizza** [comment]
this is a valid issue. im having the same problem. how do u fix it?

**Comment by icepcp** [comment]
having the same issue too. im hosting nebula on heroku and have tried reverting the commits to no avail

**Comment by GreenyDEV** [comment]
> this is a valid issue. im having the same problem. how do u fix it?

It's not a valid issue because no information was provided. You need to provide steps to replicate this, so we can attempt it ourselves and find a solution, and any other relevant information. You cannot open a ticket and expect to get help with "it doesnt work please help!!!!11!" 

Also, this is more than likely an issue with the platforms you are trying to host on.

**Comment by GreenyDEV** [comment]
> having the same issue too. im hosting nebula on heroku and have tried reverting the commits to no avail

Heroku's TOS disallows the usage of proxies, VPNs, tunnels and media proxies, etc.

**Comment by GreenyDEV** [comment]
Update: This is an issue with bare, and We're looking into a fix.

**Comment by zek-c** [comment]
> Update: This is an issue with bare, and We're looking into a fix.
well damn took you long enough to realize i switch to ultraviolet already its better

**Comment by GreenyDEV** [comment]
Ultraviolet also uses bare, we just had to update it in our dependencies.

**Comment by joemama7346** [comment]
when i try deploying a nebula like how my freind taught me now it starts saying 
Failed to load https://www.google.com/search?q=roblox Internal Server Error Code:	SyntaxError SyntaxError: Unexpected end of JSON input Try: Checking your internet connection Verifying you entered the correct address Clearing the site data Contacting bestbasketballplayer.onrender.com's administrator Verify the Bare server isn't censored If you're the administrator of bestbasketballplayer.onrender.com, try: Restarting your Bare server Updating Ultraviolet Troubleshooting the error on the GitHub repository 
Reload 
Ultraviolet v1.0.8-beta

**Comment by GreenyDEV** [comment]
Hi there! We've Identified this issue as related to the latest version of NodeJS (node 20). Please downgrade to Node 19 or earlier while we work on a fix.
