### ISSUE TITLE
Use a systemd service instead of nohup in advanced deployment documentation

### ISSUE THREAD

**Issue by willuhmjs** [NebulaServices/Nebula#109]
I suggest making a script that generates a systemd service to run the proxy automatically on startup. This is the more common approach to having a Node server run 24/7. 

This issue deals with [this page](https://docs.nebulaproxy.io/services/nebulaweb/deployment.html)

**Comment by ProgrammerIn-wonderland** [comment]
Admittedly, using nohup was a quick solution to make it work on my system which at the time was running OpenRC Gentoo, (systemD less) and I didn't know how to make OpenRC services yet

**Comment by willuhmjs** [comment]
Whichever works on the most systems. Feel free to change the title of this issue to "use PM2" for tracking purposes.

**Comment by CountBleck** [comment]
I don't see why both/all options can be provided.

For ease of use, pm2 (as much as I *personally* would like to avoid it) is the best choice for the majority reading that docs page. pm2 supports starting itself on boot through an enabled systemd service. Power users can always write their own systemd service with ease.

By the way, "systemd", not "systemD".

**Comment by ProgrammerIn-wonderland** [comment]
Pedantic as ever blu

**Comment by Riftriot** [comment]
Closed as stale
