### ISSUE TITLE
Remove Replit deployment option...

### ISSUE THREAD

**Issue by jangodev** [NebulaServices/Nebula#116]
...and any other service preventing the deployment of proxies on their platform. Too many people ask for help on this, which should just be common sense, yet it seems like removing the deployment option on readme.txt would do us all a favor.

**Comment by GreenyDEV** [comment]
Attach a PR if you can, otherwise it will be in v8 further down the line

**Comment by CountBleck** [comment]
Can you get me a list of services? I can make a PR to remove them (or you can lol)

**Comment by GreenyDEV** [comment]
Replit, Heroku, Sylo(trol)

**Comment by jangodev** [comment]
> Can you get me a list of services? I can make a PR to remove them (or you can lol)

replit, render, heroku
