### ISSUE TITLE
Heroku blocks Nebula

### ISSUE THREAD

**Issue by WifiRouterYT** [NebulaServices/Nebula#12]
I'm unable to deploy to Heroku because I get this error. Not sure what else to write here.
![image](https://user-images.githubusercontent.com/45213292/191551677-fe3928ec-1c25-4029-b873-52770b7991ad.png)

**Comment by cohenerickson** [comment]
Proxies are against the Heroku TOS, there is nothing we can do about this.

**Comment by WifiRouterYT** [comment]
so why is there an option to deploy to it? 🤨

**Comment by GreenyDEV** [comment]
if you want to fork this and deploy to heroku, u might be able to but you'll get banned (ig)
