### ISSUE TITLE
Error when deploying on Railway

### ISSUE THREAD

**Issue by DerekEpicGamer** [NebulaServices/Nebula#126]
Whenever I try to deploy on Railway, I get: 
====================================
﻿Banned Dependency Detected!
﻿====================================
﻿ 
﻿ultraviolet
﻿ultraviolet
﻿ 
﻿Please remove this dependency from your project to use it on Railway

How do I fix this?

**Comment by GreenyDEV** [comment]
You can't remove it.

**Comment by DerekEpicGamer** [comment]
Is there anyway to quickly deploy without getting flagged?
