### ISSUE TITLE
Is there anyway to quickly deploy without getting flagged?

### ISSUE THREAD

**Issue by DerekEpicGamer** [NebulaServices/Nebula#127]
If not then how do I deploy it easily

**Comment by GreenyDEV** [comment]
What???

**Comment by DerekEpicGamer** [comment]
Whenever you deploy it, it says that it's against ToS. I want to know how to bypass it.

**Comment by GreenyDEV** [comment]
we're not going to provide you how to bypass, and then break their TOS.
