### ISSUE TITLE
Discord.com login doesn't work

### ISSUE THREAD

**Issue by lumauser** [NebulaServices/Nebula#138]
In the docs it said Ultraviolet works but only osana works. Even though with osana it does reach the login screen for discord but doesn't login. In the docs it said both of them discord works on both of them.

**Comment by AverageJuliet** [comment]
ur doing it wrong

**Comment by lumauser** [comment]
> ur doing it wrong 

Do you know what I'm doing wrong by any chance? The only setting I changed was ultraviolet to Osaka since ultraviolet doesn't work for some reason

**Comment by AverageJuliet** [comment]
ur doing it wrong

**Comment by lumauser** [comment]
> ur doing it wrong

I just changed some of the settings and I works now for some reason thanks!!!
