### ISSUE TITLE
How do i deploy to github pages

### ISSUE THREAD

**Issue by hankypoo7** [NebulaServices/Nebula#145]
guys ngl im an idiot and I want to deploy this to my github pages site. how would i do it?

**Comment by 7ht** [comment]
You can't, GH pages only allows static websites unfortunately

**Comment by Riftriot** [comment]
Set the UV config to an external bare server

**Comment by Hankypoo7** [comment]
> Set the UV config to an external bare server

how

**Comment by Hankypoo7** [comment]
> You can't, GH pages only allows static websites unfortunately
oh thanks

**Comment by Riftriot** [comment]
> > Set the UV config to an external bare server
> 
> how

By editing the config. 7ht is wrong, it's possible

**Comment by Hankypoo7** [comment]
> > > Set the UV config to an external bare server
> > 
> > 
> > how
> 
> By editing the config. 7ht is wrong, it's possible

what would i specificly do? this is the code so tell me what i can change it to:


self.__uv$config = {
  prefix: "/service/go/",
  bare: "/bare/",
  encodeUrl: Ultraviolet.codec.xor.encode,
  decodeUrl: Ultraviolet.codec.xor.decode,
  handler: "/uv/uv.handler.js",
  bundle: "/uv/uv.bundle.js",
  config: "/uv/uv.config.js",
  sw: "/uv/uv.sw.js"
};

**Comment by Riftriot** [comment]
Change the bare to https://tomp.app or another bare server

**Comment by Hankypoo7** [comment]
> Change the bare to https://tomp.app or another bare server

so: 

self.__uv$config = {
prefix: "/service/go/",
bare: "https://tomp.app",
encodeUrl: Ultraviolet.codec.xor.encode,
decodeUrl: Ultraviolet.codec.xor.decode,
handler: "/uv/uv.handler.js",
bundle: "/uv/uv.bundle.js",
config: "/uv/uv.config.js",
sw: "/uv/uv.sw.js"
};

right? im 13 so im still learning js

**Comment by Riftriot** [comment]
Yup

**Comment by Hankypoo7** [comment]
> Yup

thanks. So i fork it, change that, then what? how do i deploy it to github pages
also thank you so much for helping me i really appriciate it you cool asf sorry for being annyoing

**Comment by Riftriot** [comment]
I'm not sure, I've never deployed to GH pages before. You should be able to just upload the static files and then use the proxy

**Comment by Hankypoo7** [comment]
> I'm not sure, I've never deployed to GH pages before. You should be able to just upload the static files and then use the proxy

ok thanks

**Comment by Esfirr** [comment]
> Set the UV config to an external bare server

Where is the UV config?

**Comment by Hankypoo7real** [comment]
> > Set the UV config to an external bare server
> 
> Where is the UV config? edit: nvm found itttt <3

did you ever find out how to do this? im too dumb

**Comment by Hankypoo7real** [comment]
> I'm not sure, I've never deployed to GH pages before. You should be able to just upload the static files and then use the proxy
how would i upload the static files and what do i upload lol

**Comment by tuta-amb** [comment]
This thread is pretty confusing so let me explain it to anyone who's confused.

**Can you deploy to Github Pages?**
Yes, but no. While technically you can deploy to Github Pages, Github Pages is a _static site host_. This means that it can only serve files, and it is not capable of running any backend server code.

The way proxies work is that the request is forwarded to a server. The server then grabs the data and sends it back to the client. Github Pages is only capable of the client part, not the server.

**Someone (@Riftriot) said it could be done though!**
Their solution was to edit the client so that instead of expecting Github Pages to provide a server, it would use someone else's external server. The issue is that if that server is blocked (it probably is), the client is useless since it can't connect.

**Comment by Hankypoo7real** [comment]
@tuta-amb do you have any suggestions to host this then? a lot of them like replit are blocked

**Comment by tuta-amb** [comment]
@Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.

**Comment by Hankypoo7real** [comment]
> @Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.
> 
> 
> 
> Also on some blockers, no IP addresses are blocked at all, so if you start up a proxy on your home computer, you can connect to it with the IP address.

Yeah I have render and aws, I just am not sure how to fully deploy it. I select the repo and I have to enter build commands and other stuff. I do npm I and npm start and stuff,but it doesn't work. Also, I have the student plan on GitHub so I get 180 hours on codespaces per month, but when I open it up in codespaces nothing works and it always looks like css isn't working. Thank you a lot again.

**Comment by tuta-amb** [comment]
> > @Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.
> > Also on some blockers, no IP addresses are blocked at all, so if you start up a proxy on your home computer, you can connect to it with the IP address.
> 
> Yeah I have render and aws, I just am not sure how to fully deploy it. I select the repo and I have to enter build commands and other stuff. I do npm I and npm start and stuff,but it doesn't work. Also, I have the student plan on GitHub so I get 180 hours on codespaces per month, but when I open it up in codespaces nothing works and it always looks like css isn't working. Thank you a lot again.

If you are running on a site such as Render, first you probably need to fork the repository to your own account. Then link your Github account in Render and create a new Web Service. Using instructions from [here](https://github.com/NebulaServices/Nebula?tab=readme-ov-file#server-configuration), we can see that you need to select Nodejs for the runtime, set the build command to `npm ci` and the start command to `node .` or `npm start`.

Similar, to deploy using Codespaces you should create a Codespaces using this repository. Then run:
```
# cd Nebula (if necessary)
$ npm install
$ npm ci
$ npm start
```

LMK if this works.

**Comment by Hankypoo7real** [comment]
> > > @Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.
> > > Also on some blockers, no IP addresses are blocked at all, so if you start up a proxy on your home computer, you can connect to it with the IP address.
> > 
> > 
> > Yeah I have render and aws, I just am not sure how to fully deploy it. I select the repo and I have to enter build commands and other stuff. I do npm I and npm start and stuff,but it doesn't work. Also, I have the student plan on GitHub so I get 180 hours on codespaces per month, but when I open it up in codespaces nothing works and it always looks like css isn't working. Thank you a lot again.
> 
> If you are running on a site such as Render, first you probably need to fork the repository to your own account. Then link your Github account in Render and create a new Web Service. Using instructions from [here](https://github.com/NebulaServices/Nebula?tab=readme-ov-file#server-configuration), we can see that you need to select Nodejs for the runtime, set the build command to `npm ci` and the start command to `node .` or `npm start`.
> 
> Similar, to deploy using Codespaces you should create a Codespaces using this repository. Then run:
> 
> ```
> # cd Nebula (if necessary)
> $ npm install
> $ npm ci
> $ npm start
> ```
> 
> LMK if this works.

codespaces says "error processing your request"
and render says "this action is not allowed"

**Comment by Hankypoo7real** [comment]
> > > @Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.
> > > Also on some blockers, no IP addresses are blocked at all, so if you start up a proxy on your home computer, you can connect to it with the IP address.
> > 
> > 
> > Yeah I have render and aws, I just am not sure how to fully deploy it. I select the repo and I have to enter build commands and other stuff. I do npm I and npm start and stuff,but it doesn't work. Also, I have the student plan on GitHub so I get 180 hours on codespaces per month, but when I open it up in codespaces nothing works and it always looks like css isn't working. Thank you a lot again.
> 
> If you are running on a site such as Render, first you probably need to fork the repository to your own account. Then link your Github account in Render and create a new Web Service. Using instructions from [here](https://github.com/NebulaServices/Nebula?tab=readme-ov-file#server-configuration), we can see that you need to select Nodejs for the runtime, set the build command to `npm ci` and the start command to `node .` or `npm start`.
> 
> Similar, to deploy using Codespaces you should create a Codespaces using this repository. Then run:
> 
> ```
> # cd Nebula (if necessary)
> $ npm install
> $ npm ci
> $ npm start
> ```
> 
> LMK if this works.

![image](https://github.com/NebulaServices/Nebula/assets/145811689/8ba871fb-5696-463f-b3a2-2f5d3face8e9)

**Comment by Hankypoo7real** [comment]
just got codespaces to work

**Comment by tuta-amb** [comment]
> just got codespaces to work

nice

**Comment by tuta-amb** [comment]
> > > > @Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.
> > > > Also on some blockers, no IP addresses are blocked at all, so if you start up a proxy on your home computer, you can connect to it with the IP address.
> > > 
> > > 
> > > Yeah I have render and aws, I just am not sure how to fully deploy it. I select the repo and I have to enter build commands and other stuff. I do npm I and npm start and stuff,but it doesn't work. Also, I have the student plan on GitHub so I get 180 hours on codespaces per month, but when I open it up in codespaces nothing works and it always looks like css isn't working. Thank you a lot again.
> > 
> > 
> > If you are running on a site such as Render, first you probably need to fork the repository to your own account. Then link your Github account in Render and create a new Web Service. Using instructions from [here](https://github.com/NebulaServices/Nebula?tab=readme-ov-file#server-configuration), we can see that you need to select Nodejs for the runtime, set the build command to `npm ci` and the start command to `node .` or `npm start`.
> > Similar, to deploy using Codespaces you should create a Codespaces using this repository. Then run:
> > ```
> > # cd Nebula (if necessary)
> > $ npm install
> > $ npm ci
> > $ npm start
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > LMK if this works.
> 
> ![image](https://user-images.githubusercontent.com/145811689/278061996-8ba871fb-5696-463f-b3a2-2f5d3face8e9.png)

Most likley your account is flagged as "suspicious".

**Comment by Hankypoo7real** [comment]
> > > > > @Hankypoo7 Try render.com was a good one until it got blocked, it's free tier is generous and its a relatively newer one, so it shouldn't be blocked for you. Also, if you have access to a credit card, Google Cloud, AWS, IBM Cloud, and I think Cyclic are all good ones, they just require a credit card verification. Finally, you can also run the app on Github Codespaces, because it can expose ports to the public, but you only get 50 hours of usage per month.
> 
> > > > > Also on some blockers, no IP addresses are blocked at all, so if you start up a proxy on your home computer, you can connect to it with the IP address.
> 
> > > > 
> 
> > > > 
> 
> > > > Yeah I have render and aws, I just am not sure how to fully deploy it. I select the repo and I have to enter build commands and other stuff. I do npm I and npm start and stuff,but it doesn't work. Also, I have the student plan on GitHub so I get 180 hours on codespaces per month, but when I open it up in codespaces nothing works and it always looks like css isn't working. Thank you a lot again.
> 
> > > 
> 
> > > 
> 
> > > If you are running on a site such as Render, first you probably need to fork the repository to your own account. Then link your Github account in Render and create a new Web Service. Using instructions from [here](https://github.com/NebulaServices/Nebula?tab=readme-ov-file#server-configuration), we can see that you need to select Nodejs for the runtime, set the build command to `npm ci` and the start command to `node .` or `npm start`.
> 
> > > Similar, to deploy using Codespaces you should create a Codespaces using this repository. Then run:
> 
> > > ```
> 
> > > # cd Nebula (if necessary)
> 
> > > $ npm install
> 
> > > $ npm ci
> 
> > > $ npm start
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > LMK if this works.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/145811689/278061996-8ba871fb-5696-463f-b3a2-2f5d3face8e9.png)
> 
> 
> 
> Most likely your account is flagged as "suspicious".

Oh. Why do you think that would be?

**Comment by tuta-amb** [comment]
@Hankypoo7 What kind of email are you using? Using a disposable email such as from mail.com or a temporary email such as 10MinuteMail most likely would get you flagged.

**Comment by Hankypoo7real** [comment]
@tuta-amb school email

**Comment by Hankypoo7real** [comment]
i just tryed a icloud one too.
Im gonna try a yahoo now

**Comment by tuta-amb** [comment]
@Hankypoo7 Oh wait sorry. It seems that render has implemented anti-proxy detection. 🤷‍♂️

**Comment by tuta-amb** [comment]
If Render doesn't work, I guess just stick to Codespaces then.

**Comment by Hankypoo7real** [comment]
it didnt work, but i took your repo and deployed it to cyclic [here](https://tame-pink-newt-wig.cyclic.app/uv/service/hvtrs8%2F-wuw%2Cgmoelg.aoo%2Fqopr%7B%2Fknfez%3Faoltknwe%3Fhvtrs8%2F-wuw%2Cgmoelg.aoo%2Fqecrah'3Dq'3Fhk%26s%3DGgSD%5BylpEOdX7aiGKjCEOiuq3kwNT_OQrxk8jfhDTJjmuOREeW5XuHRTnND51h3lu-1ymg%2FE%3BDpiNiz2ZcWyCXHaCUO), and it just shows me this 
![image](https://github.com/NebulaServices/Nebula/assets/145811689/602928c2-acf6-4aca-bf1a-bdcd461573cf)
It doesnt even let me do the captcha. When i look at yours [here](https://inquisitive-calf-knickers.cyclic.app/uv/service/hvtrs8%2F-wuw%2Cgmoelg.aoo%2Fqecrah%3Dq%3Fhk%23kp%3F1), it works perfectly. how do i do that?
![image](https://github.com/NebulaServices/Nebula/assets/145811689/3962fc0b-9b8e-48a7-9722-771941a24232)

**Comment by tuta-amb** [comment]
@Hankypoo7real What do you mean? What are you doing differently in each scenario?

**Comment by Hankypoo7real** [comment]
@tuta-amb i took your deployed link (on cyclic) and that worked, but when I forked your project and deployed it to cyclic, it gave me that

**Comment by tuta-amb** [comment]
@Hankypoo7real Are you able to complete the reCaptcha? Also, is @Hankypoo7 and @Hankypoo7real the same person.

**Comment by Hankypoo7real** [comment]
> @Hankypoo7real Are you able to complete the reCaptcha? Also, is @Hankypoo7 and @Hankypoo7real the same person.

No, it doesn't let me do the captcha and yes, this is my school acc the other is my personal account

**Comment by tuta-amb** [comment]
@Hankypoo7real I'm not sure. If the deploy link is working though, is there any problem with that?
