### ISSUE TITLE
Nebula Not Working In fl0.io

### ISSUE THREAD

**Issue by Devispro45** [NebulaServices/Nebula#147]
I attempted to deploy my project on fl0.io, but encountered an issue. When I entered the URL in the address bar, it displayed an error message stating, "Nebula is loading your content with the following error: SyntaxError: Unexpected token 'u', "upstream c"... is not valid JSON."

I was running the project on port 3000 and had set up everything using Docker with default configurations. I'm not very experienced in troubleshooting such issues, so I would greatly appreciate any assistance in resolving this problem. Thank you in advance!

**Comment by tuta-amb** [comment]
What is fl0.io

**Comment by Riftriot** [comment]
This is not the place to ask for help deploying, you can join our discord server for that at https://discord.gg/unblocker . This is for reporting bugs with the software
