### ISSUE TITLE
how to deploy thru aws

### ISSUE THREAD

**Issue by hankypoo7old1** [NebulaServices/Nebula#151]
i need help

**Comment by G0dvv** [comment]
Install node.js and AWS SDK for Javascript

**Comment by G0dvv** [comment]
I'm trying to do the same thing

**Comment by Riftriot** [comment]
This is not the place to ask for help deploying, you can join our discord server for that at https://discord.gg/unblocker . This is for reporting bugs with the software

**Comment by hankypoo7old1** [comment]
> This is not the place to ask for help deploying, you can join our discord server for that at https://discord.gg/unblocker . This is for reporting bugs with the software

but i dont have discord
