### ISSUE TITLE
Getting issues using actual imput

### ISSUE THREAD

**Issue by NoNameGamerOnline** [NebulaServices/Nebula#208]
When i use this and deploy it to vercel.com it does not allow web pages to be opened claiming its not found

**Comment by Riftriot** [comment]
Please read #70 . This is not the place to ask for help hosting, please ask for help in our discord server. Issues are for issues with the source code ONLY. Please do not make another issue that isn't a source code issue or you will be blocked from the org

**Comment by NoNameGamerOnline** [comment]
Sorry I saw that after I posted this sorry for wasting your time

**Comment by Riftriot** [comment]
You're good
