### ISSUE TITLE
Cannot read properties of undefined (reading 'controller')

### ISSUE THREAD

**Issue by Salty-Coder** [NebulaServices/Nebula#238]
When opening the webpage, I see the icon for a short period of time before fading to a black screen.
I get this error in the console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'controller')
    at routes-DStrMdar.js:1:138039
```
originating from this line:
```
Up(navigator.serviceWorker.controller);
```

**Comment by Salty-Coder** [comment]
> Are you running with https? Nebula will not work without a valid SSL certificate

I originally had this issue running on http, so I set up Nebula with an SSL using Nginx. Now the issue is still present when visiting the https version.

**Comment by Riftriot** [comment]
Closing as stale.
