### ISSUE TITLE
some problems, and suggestion

### ISSUE THREAD

**Issue by suzumiya39** [NebulaServices/Nebula#240]
I running Nebula on ubuntu, proxyed by nginx, and Browser is Chrome 122.
Also, I have a some problem and suggestion.

1. Console said "Client decided to terminate with reason 1".
2. When I Use Ultraviolet, return error "there are no bare clients" on first connection.
3. Other than bare+Ultraviolet will not work.
4. When I access youtube from DuckDuckGo, it returns 404. 
Then fowad to the home page from the Youtube logo, "/~/uv/...." and the bar disappears. (Google is fine)
6. I get loggined on the first search.(Like "/~/go/...")
7. When I try to navigate to a different page from the Google search bar, I get "TypeError: Failed to construct 'URL': Invalid URL" error (DuckDuckgo too)
8. Can`t find HTTP proxy configuration.
9. Connection is dropped on video loading.
--- suggestion
10. Allow the URL to be changed from the bar.
11. Even if can change the tab, it will be logged on the first access, so bypass this.
12. Allow configuration of port numbers, default search engines, from configuration file.
13. Show progress bar.

If you need screenshot, I will take it.
Can fix this?

P.S. Now that I look at it, it was quite a lot, so you can take your time to answer. sorry.

**Comment by suzumiya39** [comment]
Thank you for confirming, Riftriot.
I anser your questions. 

no bare clients issue should be fixed, I don't know why it's still happening but I'll look into it > When I tried windows 10, Does display "Worker Register page". But,chromebook didn't display it. I think this is reason.

again, it should work and I am confused on why it does it..it does work fine for me, what device are you testing on by chance and browser?  > Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36. So, Chrome 122 by HP ChromeBook.

I'm confused on what you mean by loggined on the first search. > That means that if search from the search field on the home page by chrome, it will be logged.

issue with the encoding > that mean [this](https://stackoverflow.com/questions/58111929/why-i-get-malformed-utf-8-data-error-on-crypto-js)?

http proxies have actually been removed in a recent update lol. There wasn't enough demand for keep them in and uv with wisp would've had to been worked on more to add them back > lol. ok Roger that. I will use vpn. Also think you should remove that item from the FQA. I'll send you that pull request if you need it. 

yeah YouTube has a few issues when you skip around fast, I'll try and iron out bugs sometimes soon and hopefully everything should work soon, unless you mean all videos. what videos were you watching? YouTube, Vimeo, etc.. > 
I watched [nicovideo]() and [youtube]()

suggestions > It is my personal wish, so please implement it at your discretion.

**Comment by suzumiya39** [comment]
sorry found more problem

Even if it is set to embed in the settings, it create a new tab with an anchor link.
can`t stream live.nicovideo.jp

**Comment by suzumiya39** [comment]
```
upstream nebula {
   server 127.0.0.1:8080;
}

server {
   server_name hoge.jp;
   
    listen 10443 ssl;
    ssl_certificate     /etc/ssl/server.crt;
    ssl_certificate_key /etc/ssl/private.key;

   location / {
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'Upgrade';
      proxy_connect_timeout 10;
      proxy_send_timeout 90;
      proxy_read_timeout 90;
      proxy_buffer_size 128k;
      proxy_buffers 4 256k;
      proxy_busy_buffers_size 256k;
      proxy_temp_file_write_size 256k;

      proxy_pass http://nebula;
   }
 }
 
 ... mine another server
 ```
 
 This configuration is tak from the Ultrabiolet wiki.

**Comment by suzumiya39** [comment]
I just wanted to say that the bare client works in a manner of speaking.

sorry, my english is bad..
Ok, let's isolate and explain.

bare = does work. but it had problem with no bare clients issue on first search.
![no_bare_server](https://github.com/NebulaServices/Nebula/assets/165246341/05a5aeee-1f51-4447-ae54-441b80a99fdc)

eproxy and dynamic(rammerhead)  = doesn`t work. broken layout (screen shot No.2)
![eproxy_and_dynamic_at_duckduckgo](https://github.com/NebulaServices/Nebula/assets/165246341/e3a26efb-72b1-4884-b3c4-9faa7ab9a4f4)

common issue = Invalid URL error
![url_err](https://github.com/NebulaServices/Nebula/assets/165246341/6aa53d11-4859-4a20-be31-f6ab06cf4e8f)

**Comment by Fauzanmhr** [comment]
i have same problem to :(

**Comment by suzumiya39** [comment]
It's ok.
If you have a questions to me, I will anser.

**Comment by suzumiya39** [comment]
Thank you and please do it.
I will try nebula late.

**Comment by Riftriot** [comment]
hmmm.. that's strange. ill continue looking into it

**Comment by suzumiya39** [comment]
thank you Riftriot.

In case you're interested, here's an excerpt from a help center I sent back to dmm.
1. remove cache (I tried. but not working)
2. reboot modem(= HGW) and router (not tried because my netwrok is semi static IP)
3. play to another browser (not tried because my chromebook is not allow to new application install.)
4. chromebook is deprecated. so try another computer. 

I would like to help you with inspectors, but my google organization does not allow it,,
So I will try to do it from a virtual environment if possible. (Please let us know if you have any recommendations for download sites.)
