### ISSUE TITLE
.io sites are banned; are we allowed to clone and deploy this open source code 

### ISSUE THREAD

**Issue by AbdullahDaGoat** [NebulaServices/Nebula#241]
Hey there

Nebulaproxy.io is normally banned on school websites. This is because github runs on github.io and teachers know this so they have issued bans on .io sites. Are we allowed to clone / fork this repository and deploy it to hosting sites like vercel and heroku with our own domains so we can bypass this.

Since this is copyrighted, I dont want to do something unethical!

**Comment by AbdullahDaGoat** [comment]
Sorry im aware we can contribute but alongside contributions can we also publish it as long as we cite / link this repo as the official one :)

**Comment by ading2210** [comment]
Nebula is licensed under the [GNU AGPL v3](https://www.gnu.org/licenses/agpl-3.0.en.html), so you're allowed to do this.

**Comment by VenomousSteam81** [comment]
💀 imagine asking this

**Comment by ading2210** [comment]
It's a fair question considering that the repository doesn't have a license file.
