### ISSUE TITLE
Client decided to terminate with reason 2

### ISSUE THREAD

**Issue by Anti-Apple4life** [NebulaServices/Nebula#244]
When opening Infinite Craft, this error appears in the terminal multiple times until http requests do not work anymore. Refreshing the page inside Nebula yields no better resuls. I am running Nebula in a Proxmox lxc and forwarding it to the internet with nginx

**Comment by Riftriot** [comment]
This is actually standard logging functionality and not an error. I plan to disable it soon; but it is not the cause of your problem

**Comment by ading2210** [comment]
Note that close reason 2 means that there is no error in the connection, according to the Wisp protocol specification. You can safely ignore these messages.

> 0x02 - Voluntary stream closure, which would equate to one side resetting the connection.

https://github.com/MercuryWorkshop/wisp-protocol/blob/main/protocol.md#server-only-close-reasons
