### ISSUE TITLE
Add the `hacktoberfest` label

### ISSUE THREAD

**Issue by 3kh0** [NebulaServices/Nebula#25]
Add the `hacktoberfest` label for those participating in the challenge

**Comment by GreenyDEV** [comment]
??

**Comment by 3kh0** [comment]
Go to the code tab, click on the settings icon above the description, and type in `hacktoberfest`. It is for this: https://hacktoberfest.com/ and my pr #23. I want it to count for the challenge

**Comment by GreenyDEV** [comment]
done 👍

**Comment by 3kh0** [comment]
ty
