### ISSUE TITLE
Is Nebula down?n

### ISSUE THREAD

**Issue by Shadow-Von-Eldritch** [NebulaServices/Nebula#255]
Is Nebula currently down right now since I can't access what I want from the web proxy server???

**Comment by Entrpix** [comment]
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients
There are no bare clients

**Comment by Shadow-Von-Eldritch** [comment]
what are bare clients?

**Comment by Riftriot** [comment]
No
![image](https://github.com/NebulaServices/Nebula/assets/117926989/46b0abc1-b95c-469e-b08b-796edfb44adb)
