### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by 1coolmatt8083** [NebulaServices/Nebula#257]
![Screenshot 2024-05-07 1 16 25 PM](https://github.com/NebulaServices/Nebula/assets/162379962/766eeec5-22cc-403a-a108-de9fc9dabad8)

**Comment by MotorTruck1221** [comment]
Nebula was not made to be run on Vercel, use a normal VPS

**Comment by 1coolmatt8083** [comment]
k
which one do u perfer

**Comment by 3kh0** [comment]
no

**Comment by 1coolmatt8083** [comment]
??

**Comment by 1coolmatt8083** [comment]
no?

**Comment by MotorTruck1221** [comment]
> k which one do u perfer

Google it.

GitHub isn't discord and as such, you should be asking these questions in the [discord](https://discord.gg/unblocker)
