### ISSUE TITLE
Does nebula work if I download it as a zip and host it locally

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [NebulaServices/Nebula#262]
Just wondering

**Comment by Anti-Apple4life** [comment]
rtfm

https://github.com/NebulaServices/Nebula/blob/main/README.md

**Comment by rifting** [comment]
Yes, nebula will work if you download it as a zip and host it locally. This is a non-issue. please ask these types of questions on our discord server

**Comment by ImmediateMurderProfessionals** [comment]
What file do I open to host it locally

**Comment by ImmediateMurderProfessionals** [comment]
Because when I go to the folder and open index.html it doesn't work

**Comment by rifting** [comment]
Nebula won't work without the server

**Comment by rifting** [comment]
Not sure what you're asking. Yes, you need wifi to run nebula

**Comment by ImmediateMurderProfessionals** [comment]
i mean Nebula is blocked on my school computer.
So what I did is download Nebula as a zip and unzip it so I can localhost it.
But when I open index.html nothing happens.
(In most github sites, index.html controls everything)

**Comment by rifting** [comment]
The only proxy that will work as a download is https://github.com/e9x/spadium .

**Comment by Anti-Apple4life** [comment]
> i mean Nebula is blocked on my school computer.
> So what I did is download Nebula as a zip and unzip it so I can localhost it.
> But when I open index.html nothing happens.
> (In most github sites, index.html controls everything)

If you have any pc at home, you could run Nebula on there using npm and access it on your school computer with a cloudflare tunnel or something similar
