### ISSUE TITLE
Lightspeed blocking links 

### ISSUE THREAD

**Issue by AndrewShinIsAGreatCoder** [NebulaServices/Nebula#271]
Evrytime i go to like discord and etc lightspeed blocks it. I tried diffrent proxys, and evrything. But it still blocks it

I have the extentions
Lightspeed Classroom,
Lightspeed filter,
Lightspeed digital insight agent

all installed by admin. PLS HELP

**Comment by MotorTruck1221** [comment]
See issue: #70
