### ISSUE TITLE
Won’t search or go to links + bare server wont work.

### ISSUE THREAD

**Issue by SplitSplice** [NebulaServices/Nebula#281]
I deployed it with AWS Amplify. When going to the site, everything seems good. But when I type something into the search bar (link or search term), it doesn’t do anything. When switching to bare server + dynamic, it opened an error page or sumn.

Here’s my deployment:
https://main.d1tw8r7aeken8r.amplifyapp.com/

**Comment by SplitSplice** [comment]
Here’s the error:

`Error: Unable to fetch Bare meta: 404 <!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="/transports/bareTransport.js" defer></script>
    <script src="/uv/uv.bundle.js" defer></script>
    <script src="/uv/uv.config.js" defer></script>
    <script src="/dynamic/dynamic.config.js" defer></script>
    <script src="/localforage/localforage.min.js" defer></script> 
    <script type="module" crossorigin src="/assets/index-BwdKtiQv.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-CUjRqrYn.css">
  </head>
  <body style="margin: 0">
    <div id="app"></div>

    <script>
      if (
        new URL(Object.assign(document.createElement("a"), { href: "/" }).href)
          .password
      )
        window.location.href = window.location.href;
    </script>
    <script>
      try {
        if (
          !localStorage["auth"] &&
          new URL(document.all.rcheck.href).password
        ) {
          window.location.reload();
          localStorage["auth"] = 1;
        }
      } catch {}
    </script>
  </body>
</html> `

**Comment by SplitSplice** [comment]
btw no ultraviolet and rammerhead don’t work for me.

**Comment by rifting** [comment]
Please share the full console outputs

**Comment by SplitSplice** [comment]
> Please share the full console outputs

I can’t find a way to view console outputs in amplify.

**Comment by rifting** [comment]
I mean of the browser

**Comment by SplitSplice** [comment]
> I mean of the browser

I’m on mobile.

**Comment by rifting** [comment]
Could you switch to a PC or laptop for debugging reasons? I can't recreate this issue

**Comment by rifting** [comment]
Looks like your wisp and bare server are both 404ing. Which wisp server are you using? Is this behind nginx?

**Comment by MotorTruck1221** [comment]
@Prexry would you mind telling me which version of Nebula your using?

**Comment by Prexry** [comment]
@MotorTruck1221 v9.0.1

**Comment by SplitSplice** [comment]
> Looks like your wisp and bare server are both 404ing. Which wisp server are you using? Is this behind nginx?

The wisp server is “wss://main.d1tw8r7aeken8r.amplifyapp.com/wisp/”. Sorry for the late response.

**Comment by Prexry** [comment]
[v9.0.2](https://github.com/NebulaServices/Nebula/releases/tag/v9.0.2) fixes this

**Comment by MotorTruck1221** [comment]
> [v9.0.2](https://github.com/NebulaServices/Nebula/releases/tag/v9.0.2) fixes this

Oh! I'm glad that solved you're problem. Closing this as completed
