### ISSUE TITLE
NOT AN ISSUE BUT YALL MUST READ IMPORTANT

### ISSUE THREAD

**Issue by PrimeKidMN** [NebulaServices/Nebula#284]
it works on koyeb with no file changes!!! Instructions for dumb people:
1. Fork this repo
2. Create new koyeb service and select webservice
3. Select import from github and import your forked repo
4. Change package to dockerfile and press deploy
5. YOUR DONE

Nebula has not worked on koyeb for years and its literally the perfect platform you can do the same stuff as self hosting but you don't have to pay for a domain and stuff. And using the free plan you can host your on database. Perfect for those at school who cant get freenom and use a terminal also because freenom is shut down.

**Comment by rifting** [comment]
thanks, I will add this to the readme.
In the future please don't make an issue for things that aren't issues and contact us on our discord instead. Thank you

**Comment by rifting** [comment]
Added in https://github.com/NebulaServices/Nebula/commit/3e09ab61a5b5985eba21991adacaaab1e0c68c5f .

**Comment by PrimeKidMN** [comment]
also you did not have to put that in fast In case you rushed because that was really fast but I only said you gave me a hard time because you sounded formal and I thought it was funny so I was saying it as like a half joke but thanks anyways man

**Comment by PrimeKidMN** [comment]
Oh yeah you might also want to look into dns afraid for free domains an dynamic dns because as far as I know thats the only 100% free method right now the only issue is you have to use a shared public domain which is free except there is a bunch of them and they all work and get the job done
