### ISSUE TITLE
"Open In" setting does not work as intended

### ISSUE THREAD

**Issue by Prexry** [NebulaServices/Nebula#286]
"Embed" - works fine
"Direct" - infinite loading ???
"About:Blank" - literally hrefs you to the site
"Blob" same as above

**Comment by MotorTruck1221** [comment]
Due to the way [Bare Mux](https://github.com/mercuryworkshop/bare-mux) works, these options are no longer applicable as we have to use an embed. Sorry about the confusion I'll leave this open until I get around to removing that tile

**Comment by MotorTruck1221** [comment]
This setting is no longer available in the proxy page. Closing
