### ISSUE TITLE
POST http://[ NebulaServerIP ]:3000/ returns 405 Method Not Allowed

### ISSUE THREAD

**Issue by okawaffles** [NebulaServices/Nebula#32]
Nebula Console Info:
URL: `http://[server IP]:3000/ `
BrowserName: firefox 
IsOnline: true 
agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0, `

Server info:
Running on Ubuntu 20.04LTS (Linode) 
Node v18.12.0; all packages up-to-date

Steps to reproduce:
- Open index
- Type a URL
- Press enter

![image](https://user-images.githubusercontent.com/77750838/198742494-aa6a4e81-164f-4fdd-992b-e33471176bdf.png)

**Comment by schooldev49** [comment]
Service workers will not register or function on a HTTP domain

**Comment by okawaffles** [comment]
Oh that completely slipped my mind, will try in secure context. Thanks!
