### ISSUE TITLE
Stealth mode Errors on Nebula

### ISSUE THREAD

**Issue by ask-arim** [NebulaServices/Nebula#39]
Proof that I enabled stealth mode before doing all of this:
![Enabling stealth mode](https://user-images.githubusercontent.com/111149452/205458449-f36d136b-c24a-4989-a038-354819903f40.png)
Tab 1 when I'm trying to search on Nebula in stealth mode:
![Tab 1](https://user-images.githubusercontent.com/111149452/205458126-11d0a437-bbf4-4318-b791-b0121490c3cb.png)
Tab 2 when I'm trying to search on Nebula in stealth mode:
![Tab 2](https://user-images.githubusercontent.com/111149452/205457679-11488f12-1e10-4901-a093-5b5642f8f444.png)
Tab 1 when I'm trying to open the games on Nebula in stealth mode:
![Tab 1 (second one)](https://user-images.githubusercontent.com/111149452/205457958-d3ba9bb2-6000-4573-9228-ce5aa0d338fa.png)
Tab 2 when I'm trying to open the games on Nebula in stealth mode:
![Tab 2 (second one)](https://user-images.githubusercontent.com/111149452/205457712-91dfc9aa-5779-41d2-b65e-101c06083cb4.png)

**Comment by schooldev49** [comment]
yeah game doesnt work for me either ill look into it

**Comment by ask-arim** [comment]
ok thanks
