### ISSUE TITLE
Stealth Mode Errors on Nebula (still not fixed)

### ISSUE THREAD

**Issue by ask-arim** [NebulaServices/Nebula#43]
The Stealth Mode games button still didn't get fixed. (Proof in the video that I sent)
[Recording1.webm](https://user-images.githubusercontent.com/111149452/206010055-90e14c19-1d17-4475-a781-ef086d2cf67a.webm)

**Comment by ask-arim** [comment]
Proof that I enabled stealth mode before doing all of this:
![Enabling stealth mode](https://user-images.githubusercontent.com/111149452/205458449-f36d136b-c24a-4989-a038-354819903f40.png)
Tab 1 when I'm trying to search on Nebula in stealth mode:
![Tab 1](https://user-images.githubusercontent.com/111149452/205458126-11d0a437-bbf4-4318-b791-b0121490c3cb.png)
Tab 2 when I'm trying to search on Nebula in stealth mode:
![Tab 2](https://user-images.githubusercontent.com/111149452/205457679-11488f12-1e10-4901-a093-5b5642f8f444.png)

**Comment by schooldev49** [comment]
VPS probably didn't update yet but if you fork the github repo it should work

**Comment by GreenyDEV** [comment]
Hello! I figured out this issue with the help of a friend. This is because the required files are being forbidden by your network. We're working on a fix. Thanks for your patience :)
