### ISSUE TITLE
Error code 521 is back

### ISSUE THREAD

**Issue by ask-arim** [NebulaServices/Nebula#49]
Error code 521 is back and according to the first screenshot, you need to contact your hosting provider to let them know your web server is not responding, since you're the owner of the website.
![Screenshot 2022-12-13 120652](https://user-images.githubusercontent.com/111149452/207411243-2aae5fd0-e7b5-489b-a703-ede5ef10531b.jpg)
![Screenshot 2022-12-13 120748](https://user-images.githubusercontent.com/111149452/207411361-356452b9-8763-44d7-883b-c8d605b5f7c8.jpg)

**Comment by GreenyDEV** [comment]
Hi again. Unfortunetly there is nothing we can do because this is the github repository. If this is a concern with a site, contact a support service of the person who actually owns the site. You will be banned from this issues section if you continue to make issue posts like these.
