### ISSUE TITLE
it doesnt work on glitch

### ISSUE THREAD

**Issue by jbxskm** [NebulaServices/Nebula#57]
it doesnt work when i remix it on glitch

**Comment by 3kh0** [comment]
It does not support glitch

**Comment by dimondkingYT717** [comment]
It does support glitch

**Comment by jbxskm** [comment]
![image](https://user-images.githubusercontent.com/111071747/212922382-5ee60bb2-3d55-4c69-b084-cade0802b3bc.png)
why do you have a remix on glitch  button

**Comment by GreenyDEV** [comment]
It does support Glitch, but we're not mindreaders so we need to know what error are you getting when booting Nebula on glitch?

**Comment by jbxskm** [comment]
never mind my school blocked glitch

**Comment by GreenyDEV** [comment]
ok
