### ISSUE TITLE
Deployed on VPS

### ISSUE THREAD

**Issue by SteadyStatus21** [NebulaServices/Nebula#60]
Error:
`TypeError: Cannot read properties of undefined (reading 'length')`
Any suggestions?

Thanks!

**Comment by SteadyStatus21** [comment]
I was a bit vague with opening this issue, but it is when navigating anywhere on the site with the search bar.

**Comment by GreenyDEV** [comment]
Yeah this is a known issue. I'm working on fixing it.

**Comment by GreenyDEV** [comment]
Also could you provide your steps to reproduce?

**Comment by SteadyStatus21** [comment]
> Also could you provide your steps to reproduce?

I followed your guide on installation, with the only new thing being before I started I upgraded Ubuntu to 22.04.

**Comment by GreenyDEV** [comment]
hmm that shouldn't really be an issue. I've been looking into this for a while, and I can't really figure out how to reproduce this.

**Comment by GreenyDEV** [comment]
Okay, I think I found the issue, though i still have not been able to reproduce this issue. 

The error message is indicating that the code is trying to access the 'length' property of something that is undefined so I added a default fallback in the bareswitcher. 

This SHOULD fix it but if it doesn't please let me know. I'll keep this open for now. Feel free to close it if you want :)

**Comment by GreenyDEV** [comment]
Hi there. We're still looking into the issue.

**Comment by DapperLS-Bot-Dev** [comment]
Im having this issue too. I hosted a couple installations of nebula on glitch for me and some friends use, and half of the time it will say the indicated message above, or just say 403 Forbidden. Please fix!

**Comment by cohenerickson** [comment]
If this is still an issue, can you please provide a full stack trace?
