### ISSUE TITLE
Instagram completely doesn't work!

### ISSUE THREAD

**Issue by aaravzer** [NebulaServices/Nebula#61]
So, I tried to go to instagram on the proxy and it doesnt allow me too

**Comment by 3kh0** [comment]
what are you trying to do, text your kittens?

**Comment by RuralAnemone** [comment]
> what are you trying to do, text your kittens?

child
silence

**Comment by RuralAnemone** [comment]
@aaravzer does it just not load? (please give as many details as you can (a screen recording would be most helpful))

**Comment by aaravzer** [comment]
> @aaravzer does it just not load? (please give as many details as you can (a screen recording would be most helpful))

I put this in the wrong repo, sorry!
