### ISSUE TITLE
Nebula is slow

### ISSUE THREAD

**Issue by askarim03** [NebulaServices/Nebula#66]
Nebula takes a pretty long time to load websites, so maybe you could consider using the [Byethost](https://byet.host/) web server to make Nebula faster. No offense

**Comment by GreenyDEV** [comment]
Okay, for the LAST time here, you will be banned from this section of the GitHub if you keep opening stupid issues. This is the SOURCE CODE OPEN SOURCE REPOSITORY! Not the actual server hosting page.
