### ISSUE TITLE
Anymore links?

### ISSUE THREAD

**Issue by stupidschoolaccounts** [NebulaServices/Nebula#68]
They've all been blocked for me and I tried joining the discord while I still had a chance, .gg/unblocker but I got nothing but nfts?

**Comment by FedsterCoder** [comment]
Hey there! Please DM me on discord "Taxer#8470" I will make sure you get into the server. Sorry to hear about this. :(

**Comment by FedsterCoder** [comment]
@GreenyDEV resolved
