### ISSUE TITLE
WebSockets not working

### ISSUE THREAD

**Issue by cowingtonpost1** [NebulaServices/Nebula#71]
In either an online game or a web socket test site, web sockets do not work. 

![image](https://user-images.githubusercontent.com/51143004/215526147-adba527f-5942-4be0-8485-5e5ec75a1e32.png)

**Comment by cohenerickson** [comment]
Can you link the website you were using for this test?

**Comment by GreenyDEV** [comment]
websockets were patched in the latest update !!
