### ISSUE TITLE
Discord does not work

### ISSUE THREAD

**Issue by pecocksir** [NebulaServices/Nebula#73]
When deploying with glitch, railway, and koyeb, discord does not load.  It gets stuck on the page below after logging in.  Not a internet issue, tried on hotspot, home internet and school internet and no luck.  My settings are in the comment below.

How to reproduce: login with discord using pages from deployments.  Have not tried with official sites because you cant even log in due to hCaptcha not working properly.

![image](https://user-images.githubusercontent.com/95301666/216733315-4eb2991c-8676-4c20-8dfb-1a89ca1516c3.png)

**Comment by pecocksir** [comment]
![image](https://user-images.githubusercontent.com/95301666/216638304-7d7794dc-e85b-49d2-8fed-609ac5c2d0bf.jpg)
Also here’s a picture of my settings if that helps

**Comment by cohenerickson** [comment]
My best guess is that discord is blocking IPs from services like Glitch, Railway, and Koyeb from connecting to their WebSockets. Try to switch to using a different Bare server such as https://nebulaproxy.nebula.bio/bare/.

**Comment by pecocksir** [comment]
alright will do thanks.  was in the middle of making a ticket in the discord server idk if you saw that or not

**Comment by pecocksir** [comment]
still have the same issue

also do you know when this is gonna be fixed?
![image](https://user-images.githubusercontent.com/95301666/216773155-fdcb6c0b-be81-4fc1-9802-d5ce6a6f70f5.png)

**Comment by GreenyDEV** [comment]
We're working on a fix for that

**Comment by pecocksir** [comment]
Fixed as of the most recent update
