### ISSUE TITLE
Issue with proxy

### ISSUE THREAD

**Issue by legendcuzican13** [NebulaServices/Nebula#84]
Hi, I'm running Nebula on port 80 but I still get this error when I try to use Nebula: 
`Cannot GET /service/hvtr%3A-%2F%7Bowtwbg.aoo`

**Comment by riolubruh** [comment]
@legendcuzican13 For now use the newest tag (https://github.com/NebulaServices/Nebula/releases/tag/7.11.6).
One of the more recent commits broke something.

**Comment by GreenyDEV** [comment]
We're working on a fix now :)

**Comment by Cattn** [comment]
Will be fixed in #79

**Comment by GreenyDEV** [comment]
7.11.7 fixes this!

**Comment by legendcuzican13** [comment]
> 7.11.7 fixes this!

thanks so much!

**Comment by Shuna032** [comment]
No, it is not fixed, still the same error (i may think) @GreenyDEV @Cattn 
Cannot GET /service/go/hvtr%3A-%2Fxoobq.ko
