### ISSUE TITLE
SyntaxError: Unexpected End of JSON Input

### ISSUE THREAD

**Issue by mooncake39** [NebulaServices/Nebula#88]
I'm not sure why this happens, but when I attempt to host on Gitpod, this happens:
![image](https://user-images.githubusercontent.com/52958697/223795011-b25c0a30-f214-4054-a72a-e1876e539d7d.png)

**Comment by GreenyDEV** [comment]
@cohenerickson Radon issue

**Comment by mooncake39** [comment]
@GreenyDEV its not
any site fails

**Comment by mooncake39** [comment]
![image](https://user-images.githubusercontent.com/52958697/223805029-a57191cd-8f89-43c3-8307-0d3aaf5b019c.png)

**Comment by cohenerickson** [comment]
Set your port visibility to public inside of gitpod.

**Comment by mooncake39** [comment]
I have done that, it works, but not for Eaglercraft. Apparently, it does the "Nebula is loading your content," thing when you go from the eaglercraft.ru site and click "Launch" which does not happen on other proxies that work. A friend of mine told me it was a very small change that is super important, but I'm not sure what it is. Can anybody please help?

**Comment by GreenyDEV** [comment]
wait im not too sure what the problem is at this point?

**Comment by mooncake39** [comment]
No, im not getting the initial error, but im getting this loading screen when im in eaglercraft.ru and i click 1.8.8, resent, and "launch". This loading page normally doesnt happen, but i know it is a small thing since my friend told me that it is small and very important and will make the proxy eagler-compatible. the proxy works with other sites i have tested but not eaglercraft.

The Loading page i dont normally get:
![image](https://user-images.githubusercontent.com/52958697/223915469-830505bb-f824-4c4c-93ac-a97f400dd8b9.png)

**Comment by mooncake39** [comment]
Nevermind, i have figured it out. Thanks for your help!

**Comment by CodingCody-1** [comment]
> Nevermind, i have figured it out. Thanks for your help!

What was the issue then? I seem to be having the same one.

**Comment by GreenyDEV** [comment]
I'm still really not sure

**Comment by schooldev49** [comment]
The issue here is that the project is using a beta NodeJS feature (assert type json) which is only supported after NodeJS version v17.1.0. To fix this issue, please update NodeJS on your Gitpod server

Try looking here on how to update the NodeJS version on Gitpod
https://github.com/gitpod-io/gitpod/issues/945

**Comment by schooldev49** [comment]
Assert type: json is required on all repositories importing JSON modules after NodeJS v17.5.0, so it isn't really replacable.

**Comment by CodingCody-1** [comment]
I might actually be having a different issue but when ever I try to load a site though my reverse proxy I get this: ```SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data```. However if I connect directly and bypass my reverse proxy I get this error: ```Cannot POST /```. I am using the docker container to run it. I would think that would eliminate a issue with NodeJS, at least for me.

**Comment by GreenyDEV** [comment]
is this resolved?

**Comment by CodingCody-1** [comment]
I haven't got it fixed but I think I am having a different issue.

**Comment by CodingCody-1** [comment]
I ended up fixing my issue. It was because I had password auth on in nginx. See [here](https://github.com/titaniumnetwork-dev/Ultraviolet/issues/41).

**Comment by GreenyDEV** [comment]
ah, nginx would've been a valuable piece of info
